#!/bin/bash
######################################
# THIS SCRIPT GENERATED BY GLOBAL USER
# USE THIS SCRIPT FOR FIX SSH WS 
######################################

clear
apt-get install nodejs -y 
systemctl disable ws-stunnel
systemctl disable ws
systemctl stop ws-stunnel
systemctl stop ws

# Download Node
wget -q -O websocket https://raw.githubusercontent.com/xsm-syn/fix/main/ws.js
