#!/bin/bash
######################################
# THIS SCRIPT GENERATED BY GLOBAL USER
# USE THIS SCRIPT FOR FIX SSH WS 
######################################

clear
read -p "$( echo -e "Press Enter For Starting Installation") "
echo ""

apt-get install nodejs -y >/dev/null 2>&1
systemctl disable ws-stunnel >/dev/null 2>&1
systemctl disable ws >/dev/null 2>&1
systemctl stop ws-stunnel >/dev/null 2>&1
systemctl stop ws >/dev/null 2>&1

# Download Node
wget -q -O /usr/local/bin/ws.js "https://raw.githubusercontent.com/xsm-syn/fix/main/ws.js"
chmod +x /usr/local/bin/ws.js 

# Download New Service
wget -q -O /etc/systemd/system/ws.service "https://raw.githubusercontent.com/xsm-syn/fix/main/ws-js.service"
systemctl enable ws
systemctl restart ws
rm -f ws-700.sh

echo "Done update SSH WS, Please reboot manual your VPS"
