#!/bin/bash
######################################
# THIS SCRIPT GENERATED BY GLOBAL USER
# USE THIS SCRIPT FOR FIX SSH WS 
######################################

clear
read -p "$( echo -e "Press Enter For Starting Installation") "
echo ""

apt install nodejs -y  >/dev/null 2>&1
systemctl disable ws
systemctl stop ws
wget -q -O /usr/local/bin/ws.js "https://raw.githubusercontent.com/xsm-syn/fix/main/ws.js" >/dev/null 2>&1
wget -q -O /etc/systemd/system/ws.service "https://raw.githubusercontent.com/xsm-syn/fix/main/ws-10015.service" >/dev/null 2>&1
chmod +x /usr/local/bin/*
systemctl enable ws
systemctl restart ws
systemctl restart nginx
systemctl restart ws 

echo " Done Update, Please Reboot Manual Your VPS"
